window.Zuxcyn={currentTime:0,duration:0,media:null,mediaType:null,effects:{blur:0,brightness:100,contrast:100,grayscale:0,sepia:0,saturate:100,hue:0,glow:0},keyframes:[],history:[],future:[],layers:[],activeLayer:null,projectName:"Zuxcyn Motion Project"};
const $=id=>document.getElementById(id);
let toastTimer;
window.toast=function(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),1800)};
window.snapshot=function(){return JSON.stringify({currentTime:Zuxcyn.currentTime,media:Zuxcyn.media,effects:Zuxcyn.effects,keyframes:Zuxcyn.keyframes,layers:Zuxcyn.layers})};
window.commit=function(){Zuxcyn.history.push(snapshot());if(Zuxcyn.history.length>50)Zuxcyn.history.shift();Zuxcyn.future=[]};
function restore(s){const x=JSON.parse(s);Zuxcyn.currentTime=x.currentTime;Zuxcyn.media=x.media;Zuxcyn.effects=x.effects;Zuxcyn.keyframes=x.keyframes;Zuxcyn.layers=x.layers;Zuxcyn.activeLayer=Zuxcyn.layers[Zuxcyn.layers.length-1]||null; if(window.refreshStage)refreshStage();if(window.renderEffects)renderEffects();if(window.renderKeyframes)renderKeyframes();if(window.syncInspector)syncInspector()}
function undo(){if(!Zuxcyn.history.length)return toast("Tidak ada aksi untuk Undo");const cur=snapshot();Zuxcyn.future.push(cur);restore(Zuxcyn.history.pop());toast("Undo")}
function redo(){if(!Zuxcyn.future.length)return toast("Tidak ada aksi untuk Redo");Zuxcyn.history.push(snapshot());restore(Zuxcyn.future.pop());toast("Redo")}
document.addEventListener("DOMContentLoaded",()=>{Zuxcyn.history=[snapshot()];document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab+"Tab").classList.add("active")});$("undoBtn").onclick=undo;$("redoBtn").onclick=redo;$("importBtn").onclick=()=>$("mediaInput").click();$("mediaInput").onchange=e=>{if(e.target.files[0]&&window.importMedia)importMedia(e.target.files[0])};$("exportBtn").onclick=()=>window.exportProject&&exportProject();$("addTextBtn").onclick=()=>window.addTextLayer&&addTextLayer();$("clearBtn").onclick=()=>window.clearActiveLayer&&clearActiveLayer();});
